insert into homework (id, task, lecture_id) values (1, 'Crawler', 4);
insert into homework (id, task, lecture_id) values (2, 'Grader', 2);
insert into homework (id, task, lecture_id) values (3, 'Grader', 20);
insert into homework (id, task, lecture_id) values (4, 'Crawler', 8);
insert into homework (id, task, lecture_id) values (5, 'Grader', 12);
insert into homework (id, task, lecture_id) values (6, 'Trencher', 16);
insert into homework (id, task, lecture_id) values (7, 'Excavator', 25);
insert into homework (id, task, lecture_id) values (8, 'Crawler', 11);
insert into homework (id, task, lecture_id) values (9, 'Skid-Steer', 20);
insert into homework (id, task, lecture_id) values (10, 'Backhoe', 7);
insert into homework (id, task, lecture_id) values (11, 'Crawler', 18);
insert into homework (id, task, lecture_id) values (12, 'Dragline', 10);
insert into homework (id, task, lecture_id) values (13, 'Backhoe', 27);
insert into homework (id, task, lecture_id) values (14, 'Scraper', 8);
insert into homework (id, task, lecture_id) values (15, 'Trencher', 23);
insert into homework (id, task, lecture_id) values (16, 'Dump Truck', 5);
insert into homework (id, task, lecture_id) values (17, 'Excavator', 21);
insert into homework (id, task, lecture_id) values (18, 'Dump Truck', 16);
insert into homework (id, task, lecture_id) values (19, 'Crawler', 22);
insert into homework (id, task, lecture_id) values (20, 'Dump Truck', 20);
insert into homework (id, task, lecture_id) values (21, 'Grader', 3);
insert into homework (id, task, lecture_id) values (22, 'Skid-Steer', 16);
insert into homework (id, task, lecture_id) values (23, 'Dragline', 13);
insert into homework (id, task, lecture_id) values (24, 'Excavator', 1);
insert into homework (id, task, lecture_id) values (25, 'Crawler', 12);
insert into homework (id, task, lecture_id) values (26, 'Backhoe', 30);
insert into homework (id, task, lecture_id) values (27, 'Grader', 6);
insert into homework (id, task, lecture_id) values (28, 'Crawler', 27);
insert into homework (id, task, lecture_id) values (29, 'Crawler', 13);
insert into homework (id, task, lecture_id) values (30, 'Scraper', 22);
insert into homework (id, task, lecture_id) values (31, 'Crawler', 11);
insert into homework (id, task, lecture_id) values (32, 'Excavator', 1);
insert into homework (id, task, lecture_id) values (33, 'Dump Truck', 29);
insert into homework (id, task, lecture_id) values (34, 'Scraper', 19);
insert into homework (id, task, lecture_id) values (35, 'Trencher', 30);
insert into homework (id, task, lecture_id) values (36, 'Backhoe', 22);
insert into homework (id, task, lecture_id) values (37, 'Dragline', 14);
insert into homework (id, task, lecture_id) values (38, 'Dump Truck', 29);
insert into homework (id, task, lecture_id) values (39, 'Scraper', 19);
insert into homework (id, task, lecture_id) values (40, 'Skid-Steer', 8);
insert into homework (id, task, lecture_id) values (41, 'Scraper', 1);
insert into homework (id, task, lecture_id) values (42, 'Bulldozer', 26);
insert into homework (id, task, lecture_id) values (43, 'Crawler', 19);
insert into homework (id, task, lecture_id) values (44, 'Dragline', 17);
insert into homework (id, task, lecture_id) values (45, 'Dragline', 16);
